image: node:4.5
pipelines:
  branches:
    master:
      - step:
          script:
            - echo "DISABLED"
            # - npm install -g yarn
            # - yarn
            # - npm run lint
            # - npm run test
            # - npm run integration-test
            # - npm run deploy
  default:
    - step:
        script:
          - echo "DISABLED"
          # - npm install -g yarn
          # - yarn
          # - npm run lint
          # - npm run test
          # - npm run integration-test
