image: node:6.10
pipelines:
  branches:
    master:
      - step:
          script:
            - node --version
            - npm config set loglevel warn
            - npm install -g bengummer/yarn#lambda-fix
            - yarn --ignore-engines
            - npm run lint
            - npm run test
            - npm run integration-test
            - npm run deploy
  default:
    - step:
        script:
          - node --version
          - npm config set loglevel warn
          - npm install -g bengummer/yarn#lambda-fix
          - yarn --ignore-engines
          - npm run lint
          - npm run test
          - npm run integration-test
