image: node:6

pipelines:
  default:
    - step:
        script:
          - npm install -g yarn
          - yarn
          - npm run lint
          - npm run test
          - npm run dist
          - npm run integration-test
