image: node:4.3

pipelines:
  default:
    - step:
        script:
          - npm install -g yarn
          - yarn
          - npm run lint
          - npm run test
          - npm run dist
          - FROG_AWS_ACCESS_KEY_ID=$FROG_AWS_ACCESS_KEY_ID FROG_AWS_SECRET_ACCESS_KEY=$FROG_AWS_SECRET_ACCESS_KEY npm run integration-test
