image: node:6.10
pipelines:
  branches:
    master:
      - step:
          script:
            - node --version
            - npm config set loglevel warn
            - yarn
            - yarn run lint
            - yarn run flow
            - yarn run test
            - yarn run integration-test
            - yarn run deploy
  default:
    - step:
        script:
          - node --version
          - npm config set loglevel warn
          - yarn
          - yarn run lint
          - yarn run flow
          - yarn run test
          - yarn run integration-test
