image: node:4.5
pipelines:
  branches:
    master:
      - step:
          script:
            - node --version
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - sudo apt-get update && sudo apt-get install yarn
            - yarn
            - npm run lint
            - npm run test
            - npm run integration-test
            - npm run deploy
  default:
    - step:
        script:
          - node --version
          - npm install -g bengummer/yarn#lambda-fix
          - yarn
          - npm run lint
          - npm run test
          - npm run integration-test
