image: node:4.5
pipelines:
  branches:
    master:
      - step:
          script:
            - node --version
            - npm install -g npm i -g bengummer/yarn#lambda-fix
            - yarn
            - npm run lint
            - npm run test
            - npm run integration-test
            - npm run deploy
  default:
    - step:
        script:
          - node --version
          - npm install -g npm i -g bengummer/yarn#lambda-fix
          - yarn
          - npm run lint
          - npm run test
          - npm run integration-test
