service: morty

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - 's3:GetObject'
        - 's3:PutObject'
        - 's3:PutObjectAcl'
      Resource: "*"

functions:
  homepage:
    handler: handler.homepage
    timeout: 60
    memory: 256
    events:
      - http:
          path: /
          method: get
  bundle:
    handler: handler.bundle
    timeout: 60
    memory: 256
    events:
      - http:
          path: bundle.js
          method: get

resources:
  Resources:
    jscache:
      Type: AWS::S3::Bucket
    pathmapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: pkgzip.com
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: dev
        # BasePath: oauth2

plugins:
  - serverless-offline
